services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_DB=employeegadget_db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
    ports:
      - 5435:5432


